"""create application schema

Revision ID: d760594bf6a4
Revises: 
Create Date: 2026-09-06 01:11:27.240551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd760594bf6a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_protection_triggers() -> None:
    dialect = op.get_bind().dialect.name

    if dialect == "sqlite":
        op.execute("""
            CREATE TRIGGER inventory_units_inventory_id_immutable
            BEFORE UPDATE OF inventory_id ON inventory_units
            WHEN NEW.inventory_id != OLD.inventory_id
            BEGIN
                SELECT RAISE(ABORT, 'inventory_id is immutable');
            END
        """)
        op.execute("""
            CREATE TRIGGER inventory_sequence_no_delete
            BEFORE DELETE ON inventory_id_sequence
            BEGIN
                SELECT RAISE(ABORT, 'inventory ID allocations cannot be deleted');
            END
        """)
        op.execute("""
            CREATE TRIGGER label_scans_scan_id_immutable
            BEFORE UPDATE OF scan_id ON label_scans
            WHEN NEW.scan_id != OLD.scan_id
            BEGIN
                SELECT RAISE(ABORT, 'scan_id is immutable');
            END
        """)
        return

    if dialect != "postgresql":
        raise RuntimeError(f"Unsupported database dialect: {dialect}")

    op.execute("""
        CREATE FUNCTION reject_inventory_id_update() RETURNS trigger AS $$
        BEGIN
            IF NEW.inventory_id IS DISTINCT FROM OLD.inventory_id THEN
                RAISE EXCEPTION 'inventory_id is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER inventory_units_inventory_id_immutable
        BEFORE UPDATE OF inventory_id ON inventory_units
        FOR EACH ROW EXECUTE FUNCTION reject_inventory_id_update()
    """)
    op.execute("""
        CREATE FUNCTION reject_inventory_sequence_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'inventory ID allocations cannot be deleted';
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER inventory_sequence_no_delete
        BEFORE DELETE ON inventory_id_sequence
        FOR EACH ROW EXECUTE FUNCTION reject_inventory_sequence_delete()
    """)
    op.execute("""
        CREATE FUNCTION reject_scan_id_update() RETURNS trigger AS $$
        BEGIN
            IF NEW.scan_id IS DISTINCT FROM OLD.scan_id THEN
                RAISE EXCEPTION 'scan_id is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER label_scans_scan_id_immutable
        BEFORE UPDATE OF scan_id ON label_scans
        FOR EACH ROW EXECUTE FUNCTION reject_scan_id_update()
    """)


def drop_postgresql_trigger_functions() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return

    op.execute("DROP FUNCTION reject_scan_id_update()")
    op.execute("DROP FUNCTION reject_inventory_sequence_delete()")
    op.execute("DROP FUNCTION reject_inventory_id_update()")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_id_sequence',
    sa.Column('sequence_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('allocated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sequence_number'),
    sqlite_autoincrement=True
    )
    op.create_table('inventory_units',
    sa.Column('inventory_id', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.Text(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('style_code', sa.Text(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('size', sa.Text(), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_identifier', sa.Text(), server_default='', nullable=False),
    sa.Column('stockx_product_id', sa.Text(), server_default='', nullable=False),
    sa.Column('stockx_variant_id', sa.Text(), server_default='', nullable=False),
    sa.Column('sheet_row', sa.Integer(), nullable=True),
    sa.Column('sheet_sync_status', sa.Text(), nullable=False),
    sa.Column('sheet_sync_error', sa.Text(), nullable=True),
    sa.Column('discord_message_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('sheet_synced_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('discord_message_id')
    )
    op.create_index('inventory_units_sheet_row_idx', 'inventory_units', ['sheet_row'], unique=False)
    op.create_index('inventory_units_sheet_sync_status_idx', 'inventory_units', ['sheet_sync_status'], unique=False)
    op.create_table('label_scans',
    sa.Column('scan_id', sa.Text(), nullable=False),
    sa.Column('discord_message_id', sa.Text(), nullable=False),
    sa.Column('discord_attachment_id', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('barcode_results_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('raw_vision_json', sa.Text(), nullable=True),
    sa.Column('normalized_extraction_json', sa.Text(), nullable=True),
    sa.Column('market_data_json', sa.Text(), nullable=True),
    sa.Column('stockx_product_id', sa.Text(), server_default='', nullable=False),
    sa.Column('stockx_variant_id', sa.Text(), server_default='', nullable=False),
    sa.Column('validation_status', sa.Text(), server_default='received', nullable=False),
    sa.Column('warning_details_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('supplied_price', sa.Float(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.Text(), nullable=False),
    sa.Column('linked_inventory_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id'),
    sa.UniqueConstraint('discord_message_id'),
    sa.UniqueConstraint('image_sha256')
    )
    op.create_index('label_scans_message_attachment_idx', 'label_scans', ['discord_message_id', 'discord_attachment_id'], unique=True)
    op.create_index('label_scans_state_idx', 'label_scans', ['state'], unique=False)
    op.create_table('processed_stockx_orders',
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('order_number')
    )
    create_protection_triggers()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_stockx_orders')
    op.drop_index('label_scans_state_idx', table_name='label_scans')
    op.drop_index('label_scans_message_attachment_idx', table_name='label_scans')
    op.drop_table('label_scans')
    op.drop_index('inventory_units_sheet_sync_status_idx', table_name='inventory_units')
    op.drop_index('inventory_units_sheet_row_idx', table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_table('inventory_id_sequence')
    drop_postgresql_trigger_functions()
    # ### end Alembic commands ###
